# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=skrules
  matrix:

    # This environment tests the newest supported Anaconda release (4.4.0)
    # It also runs tests requiring Pandas.
    - DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
      NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1" PANDAS_VERSION="0.20.2"
      CYTHON_VERSION="0.25.2" COVERAGE=true

    # This environment use pytest to run the tests. It uses the newest
    # supported Anaconda release (4.4.0). It also runs tests requiring Pandas.
    - USE_PYTEST="true" DISTRIB="conda" PYTHON_VERSION="3.6.1"
      INSTALL_MKL="true" NUMPY_VERSION="1.13.3" SCIPY_VERSION="0.19.1"
      PANDAS_VERSION="0.20.2" CYTHON_VERSION="0.25.2"
      TEST_DOCSTRINGS="true"

    # flake8 linting on diff wrt common ancestor with upstream/master
    - RUN_FLAKE8="true" SKIP_TESTS="true" PANDAS_VERSION="0.20.2"
      DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
      NUMPY_VERSION="1.13" SCIPY_VERSION="0.19.1" CYTHON_VERSION="0.25.2"


install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
